### ISSUE TITLE
scrape_books.py: Permission denied

### ISSUE THREAD

**Issue by mateconpizza** [giomatfois62/rofi-books#1]
Hi,

After executing the `rofi-books.sh` script, I got this error:

```bash
./rofi-books.sh: line 53: /home/.../rofi-books/scrape_books.py: Permission denied
```

Adding `python3` in line 53, the error goes away or you can `chmod +x scrape_books.py` from `rofi-books.sh`

**Comment by mateconpizza** [comment]
I forgot to add this:

```bash
(process:22608): Helpers.IconFetcher-WARNING **: 15:42:48.403: Error calling thumbnailer: Failed to execute child process “/home/.../rofi-books/download_icon.sh” (Permission denied)
```

And thanks for this!

**Comment by giomatfois62** [comment]
Hey, Sorry the uploaded files didn't carry the executable bit, I'll fix it
soon when I have a minute, in the meantime you can run "chmod +x *" in the
script directory to fix it.

**Comment by mateconpizza** [comment]
Hey, thank you. I'm sorry for bothering you with this small issue, it was just in case any `rofi-books.sh` user didn't know how to move forward.

I take this opportunity to thank you for adding xdg thumbnails fetching functionality in rofi-icon-fetcher 👋

**Comment by giomatfois62** [comment]
You did well, i always forget about file permissions, and thanks for the kind words, I have a lot of fun writing these little scripts and was happy to contribute a small bit to rofi.
